# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

- name: compare package.json of current deploy with previous deploy
  command: diff {{site_path}}/package.json {{clone_path}}/package.json
  register: package_diff
  ignore_errors: true
  no_log: true

- name: copy existing npm modules
  command: cp -R {{site_path}}/node_modules {{clone_path}}
  when: package_diff.rc == 0

- name: install npm modules
  npm: path="{{clone_path}}"
  when: package_diff.rc != 0

- name: npm install
  npm:
    path: "{{clone_path}}"
  when: env != 'development'

- name: build site assets
  shell: grunt
  args:
    chdir: "{{clone_path}}"
  when: env != 'development'