#########
# SECRETS
#########

# Configure how secrets are retreived.
secret_user: "{{ lookup('env', 'USER') }}"
secret_server: nest.bocoup.com
secret_path: /mnt/secrets
secret_dest_temp: /tmp
# These files will be copied from the secret server to the dev/prod machine
secret_files:
  - src: ses.json
    dest: "{{site_path}}"